version: '3.8'

services:
  db:
    build: .
    container_name: clickdesp-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clickdesp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: